"""Tests for scripts/commit_guard.py — the pre-push identity/attribution gate.

The rules come from CLAUDE.md § Branches & Commits. They exist because the
harness presets GIT_AUTHOR_* but leaves GIT_COMMITTER_* empty, so any commit
written without explicit `-c user.*` flags silently takes the committer from
~/.gitconfig — and a rebase does that to every commit in the branch at once.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_SCRIPTS_DIR = _REPO_ROOT / "scripts"

# scripts/ is not a package — same import-path trick as test_agent_context.py.
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import commit_guard  # noqa: E402

GOOD = commit_guard.EXPECTED_IDENTITY
BAD = "Claude <noreply@anthropic.com>"
SHA = "d8ea3450846abe5fdc26e88673ef659c4b400976"


# ── identity ─────────────────────────────────────────────────────────────────

def test_correct_identity_passes() -> None:
    assert commit_guard.check_commit(SHA, GOOD, GOOD, "fix(console): tidy") == []


def test_wrong_committer_is_reported() -> None:
    # The exact failure this hook exists for: `git rebase` without -c flags
    # keeps the author and rewrites only the committer.
    problems = commit_guard.check_commit(SHA, GOOD, BAD, "fix(console): tidy")
    assert len(problems) == 1
    assert "committer" in problems[0]
    assert BAD in problems[0]


def test_wrong_author_is_reported() -> None:
    problems = commit_guard.check_commit(SHA, BAD, GOOD, "fix(console): tidy")
    assert len(problems) == 1
    assert "author" in problems[0]


def test_both_identities_wrong_are_reported_separately() -> None:
    assert len(commit_guard.check_commit(SHA, BAD, BAD, "fix: x")) == 2


def test_report_names_the_offending_commit() -> None:
    problems = commit_guard.check_commit(SHA, GOOD, BAD, "fix: x")
    assert problems[0].startswith(SHA[:9])


# ── attribution ──────────────────────────────────────────────────────────────

@pytest.mark.parametrize("message", [
    "fix: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
    "fix: x\n\nco-authored-by: someone <a@b.c>",
    "fix: x\n\nClaude-Session: https://example.test/s/1",
    "fix: x\n\ncodex-session: abc",
    "fix: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)",
    "fix: x\n\nGenerated by Codex.",
    "fix: x\n\nSee https://claude.ai/code/session_01",
])
def test_attribution_is_rejected(message: str) -> None:
    problems = commit_guard.check_commit(SHA, GOOD, GOOD, message)
    assert problems, f"should have been rejected: {message!r}"


@pytest.mark.parametrize("message", [
    # Ordinary prose must not trip the footer rule: the pattern requires a tool
    # name within 60 characters of "generated with/by".
    "feat(db): store the schema generated by the migration script",
    "fix(agent): drop the session trailer from the manifest parser",
    "refactor(console): rename ai_hint to hint",
    "test(console): run and expand the gui js suite",
])
def test_ordinary_messages_pass(message: str) -> None:
    assert commit_guard.check_commit(SHA, GOOD, GOOD, message) == []


# ── branch names ─────────────────────────────────────────────────────────────

@pytest.mark.parametrize("ref", [
    "refs/heads/claude/musubi-agent-orchestration-a1b93m",
    "refs/heads/feat/codex-port",
    "refs/heads/CLAUDE-scratch",
])
def test_tool_named_branches_are_rejected(ref: str) -> None:
    assert commit_guard.check_branch(ref)


@pytest.mark.parametrize("ref", [
    "refs/heads/fix/agent-advisory-scope-routing",
    "refs/heads/feat/console-request-runtime-history",
    "refs/heads/dev",
])
def test_product_named_branches_pass(ref: str) -> None:
    assert commit_guard.check_branch(ref) == []


# ── log parsing ──────────────────────────────────────────────────────────────

def test_parse_commits_survives_multiline_bodies() -> None:
    # A commit body wraps at 72 cols and contains blank lines; the parser must
    # not split on them, only on the record separator.
    record = (
        f"{SHA}\x1f{GOOD}\x1f{GOOD}\x1f"
        "feat(x): y\n\nbody line one\n\nbody line two\n\x1e"
    )
    commits = commit_guard.parse_commits(record)
    assert len(commits) == 1
    sha, author, committer, message = commits[0]
    assert (sha, author, committer) == (SHA, GOOD, GOOD)
    assert "body line two" in message


def test_parse_commits_handles_empty_output() -> None:
    assert commit_guard.parse_commits("") == []


# ── end to end, through a throwaway repository ───────────────────────────────

def _run_git(repo: Path, *args: str, env: dict | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, check=True, env=env,
    )


@pytest.fixture()
def repo_with_hook(tmp_path: Path) -> tuple[Path, Path]:
    """A repo whose pre-push hook is this repository's hook, plus a bare remote."""
    remote = tmp_path / "remote.git"
    subprocess.run(["git", "init", "--bare", "-q", str(remote)], check=True)

    work = tmp_path / "work"
    work.mkdir()
    _run_git(work, "init", "-q", "-b", "dev")
    _run_git(work, "remote", "add", "origin", str(remote))
    _run_git(work, "config", "core.hooksPath", str(_SCRIPTS_DIR / "git-hooks"))
    return work, remote


def _commit(repo: Path, text: str, *, name: str, email: str, message: str) -> None:
    (repo / "file.txt").write_text(text)
    _run_git(repo, "add", "file.txt")
    _run_git(
        repo,
        "-c", f"user.name={name}", "-c", f"user.email={email}",
        "commit", "-q", "-m", message,
    )


def _push(repo: Path, branch: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "push", "origin", branch],
        cwd=repo, capture_output=True, text=True,
    )


def test_hook_allows_a_clean_push(repo_with_hook: tuple[Path, Path]) -> None:
    work, _ = repo_with_hook
    _commit(work, "one", name="Eurus", email="t.hoang7895@gmail.com", message="feat(x): add y")

    result = _push(work, "dev")

    assert result.returncode == 0, result.stderr


def test_hook_refuses_a_wrong_committer(repo_with_hook: tuple[Path, Path]) -> None:
    work, remote = repo_with_hook
    _commit(work, "one", name="Claude", email="noreply@anthropic.com", message="feat(x): add y")

    result = _push(work, "dev")

    assert result.returncode != 0
    assert "push refused" in result.stderr
    assert "committer" in result.stderr
    # The push must not have landed.
    assert _run_git(remote, "branch", "--list").stdout.strip() == ""


def test_hook_refuses_an_attribution_trailer(repo_with_hook: tuple[Path, Path]) -> None:
    work, _ = repo_with_hook
    _commit(
        work, "one",
        name="Eurus", email="t.hoang7895@gmail.com",
        message="feat(x): add y\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
    )

    result = _push(work, "dev")

    assert result.returncode != 0
    assert "Co-Authored-By" in result.stderr


def test_hook_refuses_a_tool_named_branch(repo_with_hook: tuple[Path, Path]) -> None:
    work, _ = repo_with_hook
    _commit(work, "one", name="Eurus", email="t.hoang7895@gmail.com", message="feat(x): add y")
    _run_git(work, "switch", "-q", "-c", "claude/scratch-1")

    result = _push(work, "claude/scratch-1")

    assert result.returncode != 0
    assert "names a tool" in result.stderr


def test_hook_checks_only_the_commits_being_pushed(repo_with_hook: tuple[Path, Path]) -> None:
    """A bad commit already on the remote must not block a later clean push.

    Without the remote_sha..local_sha range the hook would re-scan history on
    every push and permanently wedge the branch.
    """
    work, _ = repo_with_hook
    _commit(work, "one", name="Eurus", email="t.hoang7895@gmail.com", message="feat(x): one")
    assert _push(work, "dev").returncode == 0

    # A commit that violates the rules, force-landed past the hook.
    _commit(work, "two", name="Claude", email="noreply@anthropic.com", message="feat(x): two")
    assert subprocess.run(
        ["git", "push", "--no-verify", "origin", "dev"],
        cwd=work, capture_output=True, text=True,
    ).returncode == 0

    _commit(work, "three", name="Eurus", email="t.hoang7895@gmail.com", message="feat(x): three")

    result = _push(work, "dev")

    assert result.returncode == 0, result.stderr
